@echo off
echo Formatting code...
go fmt ./...

echo Vetting code...
go vet ./...

echo Building AurumTax CLI for Windows...
set GOOS=windows
set GOARCH=amd64
go build -o aurumtax.exe ./cmd/aurumtax

echo Done!
pause
